name: tests

on: [push, pull_request]

permissions:
    contents: read

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [8.5, 8.4, 8.3]
                laravel: [12.0, 13.0]
                livewire: [3.0, 4.0]

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Livewire ${{ matrix.livewire }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
                  coverage: none

            - name: Laravel version
              run: composer require laravel/framework:^${{ matrix.laravel }} --no-update

            - name: Livewire version
              run: composer require livewire/livewire:^${{ matrix.livewire }} --no-update

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-progress

            - name: Run tests
              run: composer test
